# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0002_panier_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmde_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('payer', 'Payer'), ('exp\xe9die', 'Exp\xe9die'), ('rembourse', 'Rembourse')], default='nouvelle', max_length=250)),
                ('total_cmde', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paniers.Panier')),
            ],
        ),
    ]
