# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livraison',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=100),
        ),
    ]
