# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180501_0759'),
        ('commandes', '0002_commande_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
