# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_auto_20180326_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
